version: '3'
services:
  go.maria:
    image: 'mariadb:latest'
    ports:
      - '${DB_PORT:-33066}:33066'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_TCP_PORT: '${DB_PORT}'
      MYSQL_UNIX_PORT: '${DB_PORT}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'go-mysql:/var/lib/mysql'
    networks:
      - go
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
networks:
  go:
    driver: bridge
volumes:
  go-mysql:
    driver: local